// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCutJW2s8PUg2i78M15p2rGFQ_BOEs0wbA',
    appId: '1:328345653057:web:99780f8dd4806395735bc0',
    messagingSenderId: '328345653057',
    projectId: 'flutter66appjam',
    authDomain: 'flutter66appjam.firebaseapp.com',
    storageBucket: 'flutter66appjam.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKMfFWwI684_zj4az5PYyXtO8MUQBzILU',
    appId: '1:328345653057:android:9445419b9d9cbc15735bc0',
    messagingSenderId: '328345653057',
    projectId: 'flutter66appjam',
    storageBucket: 'flutter66appjam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcVnnEgw8cSf_Xfq4HTDpTIF2pdMVRIhU',
    appId: '1:328345653057:ios:bcba9d1c5a92b956735bc0',
    messagingSenderId: '328345653057',
    projectId: 'flutter66appjam',
    storageBucket: 'flutter66appjam.appspot.com',
    iosBundleId: 'com.example.appjamMlkit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcVnnEgw8cSf_Xfq4HTDpTIF2pdMVRIhU',
    appId: '1:328345653057:ios:57f272b6ce7194bb735bc0',
    messagingSenderId: '328345653057',
    projectId: 'flutter66appjam',
    storageBucket: 'flutter66appjam.appspot.com',
    iosBundleId: 'com.example.appjamMlkit.RunnerTests',
  );
}
